-- COST FY2019 — correction: replace all 7 balance sheet fields (FY2018 values erroneously copied)
-- Generated by /insert-financials on 2026-04-21
-- Source: SEC 10-K FY2019 (balance sheet dated 2019-09-01)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Costco', 2019, '2019-09-01',
  152703000, 132886000, 19817000, 14994000,
  4737000, 3659000, 11395000,
  23485000, 45400000, 23237000,
  29816000, 15584000, 45400000
);

-- COST FY2020 — SGA update: 16,332,000 → 16,387,000 (preopening reclassified per FY2022 restatement)
-- Generated by /insert-financials on 2026-04-21
-- Source: SEC 10-K FY2022 restated comparative column

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Costco', 2020, '2020-08-30',
  166761000, 144939000, 21822000, 16387000,
  5435000, 4002000, 12242000,
  28120000, 55556000, 24844000,
  36851000, 18705000, 55556000
);

-- COST FY2021 — SGA update: 18,461,000 → 18,537,000 (preopening reclassified per FY2022/FY2023 restatement)
-- Generated by /insert-financials on 2026-04-21
-- Source: SEC 10-K FY2022/FY2023 restated comparative column

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Costco', 2021, '2021-08-29',
  195929000, 170684000, 25245000, 18537000,
  6708000, 5007000, 14215000,
  29505000, 59268000, 29441000,
  41190000, 18078000, 59268000
);

-- COST FY2025 — new insert (year not previously in Dolt)
-- Generated by /insert-financials on 2026-04-21
-- Source: SEC 10-K FY2025 and Yahoo Finance (agree exactly)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Costco', 2025, '2025-08-31',
  275235000, 239886000, 35349000, 24966000,
  10383000, 8099000, 18116000,
  38380000, 77099000, 37108000,
  47935000, 29164000, 77099000
);
